name: Publish

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build & Publish to Maven Central
        run: chmod +x ./gradlew && ./gradlew publishAllPublicationsToMavenRepository
        env:
          PUBLISHING_USER: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          PUBLISHING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          PUBLISHING_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
          PUBLISHING_SNAPSHOT_URL: https://s01.oss.sonatype.org/service/local/content/repositories/snapshots/
          SIGN_KEY: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          SIGN_KEY_ID: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
          SIGN_KEY_PASSPHRASE: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
